name = "glance"
version = "0.7.0"
description = "A Gleam source code parser, in Gleam!"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "glance" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.28"
glexer = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.10"
simplifile = "~> 0.1"
