name = "glance"
version = "5.0.0"
description = "A Gleam source code parser, in Gleam!"
gleam = ">= 1.7.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "glance" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.28.0 and < 2.0.0"
glexer = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
pprint = ">= 1.0.4 and < 2.0.0"

# Birdie deps
justin = ">= 1.0.1 and < 2.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
rank = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
trie_again = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
edit_distance = ">= 2.0.1 and < 3.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
