name = "glance"
version = "0.8.1"
description = "A Gleam source code parser, in Gleam!"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "glance" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.28.0 and < 2.0.0"
glexer = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 0.1"
